name: assemblex
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  path_provider_android: ^2.2.18
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.0
  sqflite: ^2.4.2
  path: ^1.9.1
  image_picker: ^1.2.0
  lottie: ^3.3.2
  shared_preferences: ^2.5.3
  flutter_svg: ^2.2.1
  http: ^1.5.0
  cached_network_image: ^3.3.1
  flutter_native_splash: ^2.4.7
  mailer: ^6.1.0
  google_maps_flutter: ^2.14.0
  flutter_map: ^8.2.2
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter_native_splash:
  color: "#faffbf"          # background color you want
  image: assets/images/logo1.png   # your logo
  android: true
  ios: false                # true if you use iOS 

flutter_icons:
  android: true
  ios: false        # set true if you also want iOS
  image_path: "assets/images/logo1.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/
    - assets/fonts/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat1.ttf
          weight: 400
        - asset: assets/fonts/Montserrat1.ttf
          weight: 700